from tkinter import *

class Cell(PhotoImage):
    def __init__(self, gets, gives, name, file, deleted = False):
        PhotoImage.__init__(self, file=file, name=name)
        self.gets = gets
        self.gives = gives
        self.deleted = deleted

tk = Tk()

#ICON
appIcon = PhotoImage(file="resources/arrow_circuits_icon.ico")

#CELLS
emptyCell = Cell(gets = [], gives = [], name="EmptyCell", file="resources/empty_cell.png")
generator = Cell(gets = [], gives = ["down", "up", "left", "right"], name="Generator", file="resources/generator.png")

arrowPointingUp = Cell(gets = ["down"], gives = [], name ="ArrowPointingUp", file="resources/arrow_pUP.png")
arrowPointingDown = Cell(gets = ["up"], gives = [], name ="ArrowPointingDown", file="resources/arrow_pDOWN.png")
arrowPointingLeft = Cell(gets = ["right"], gives = [], name ="ArrowPointingLeft", file="resources/arrow_pLEFT.png")
arrowPointingRight = Cell(gets = ["left"], gives = [], name ="ArrowPointingRight", file="resources/arrow_pRIGHT.png")
electrifiedArrowPointingUp = Cell(gets = ["down"], gives = ["up"], name = "ElectrifiedArrowPointingUp", file="resources/electrified_arrow_pUP.png")
electrifiedArrowPointingDown = Cell(gets = ["up"], gives = ["down"], name = "ElectrifiedArrowPointingDown", file="resources/electrified_arrow_pDOWN.png")
electrifiedArrowPointingLeft = Cell(gets = ["right"], gives = ["left"], name = "ElectrifiedArrowPointingLeft", file="resources/electrified_arrow_pLEFT.png")
electrifiedArrowPointingRight = Cell(gets = ["left"], gives = ["right"], name = "ElectrifiedArrowPointingRight", file="resources/electrified_arrow_pRIGHT.png")

edgePointingFromDownLeft = Cell(gets = ["down"], gives = [], name = "EdgePointingFromDownLeft", file="resources/edge_fDOWN_pLEFT.png")
edgePointingFromDownRight = Cell(gets = ["down"], gives = [], name = "EdgePointingFromDownRight", file="resources/edge_fDOWN_pRIGHT.png")
edgePointingFromLeftDown = Cell(gets = ["left"], gives = [], name = "EdgePointingFromLeftDown", file="resources/edge_fLEFT_pDOWN.png")
edgePointingFromLeftUp = Cell(gets = ["left"], gives = [], name = "EdgePointingFromLeftUp", file="resources/edge_fLEFT_pUP.png")
edgePointingFromRightDown = Cell(gets = ["right"], gives = [], name = "EdgePointingFromRightDown", file="resources/edge_fRIGHT_pDOWN.png")
edgePointingFromRightUp = Cell(gets = ["right"], gives = [], name = "EdgePointingFromRightUp", file="resources/edge_fRIGHT_pUP.png")
edgePointingFromUpLeft = Cell(gets = ["up"], gives = [], name = "EdgePointingFromUpLeft", file="resources/edge_fUP_pLEFT.png")
edgePointingFromUpRight = Cell(gets = ["up"], gives = [], name = "EdgePointingFromUpRight", file="resources/edge_fUP_pRIGHT.png")
electrifiedEdgePointingFromDownLeft = Cell(gets = ["down"], gives = ["left"], name = "ElectrifiedEdgePointingFromDownLeft", file="resources/electrified_edge_fDOWN_pLEFT.png")
electrifiedEdgePointingFromDownRight = Cell(gets = ["down"], gives = ["right"], name = "ElectrifiedEdgePointingFromDownRight", file="resources/electrified_edge_fDOWN_pRIGHT.png")
electrifiedEdgePointingFromLeftDown = Cell(gets = ["left"], gives = ["down"], name = "ElectrifiedEdgePointingFromLeftDown", file="resources/electrified_edge_fLEFT_pDOWN.png")
electrifiedEdgePointingFromLeftUp = Cell(gets = ["left"], gives = ["up"], name = "ElectrifiedEdgePointingFromLeftUp", file="resources/electrified_edge_fLEFT_pUP.png")
electrifiedEdgePointingFromRightDown = Cell(gets = ["right"], gives = ["down"], name = "ElectrifiedEdgePointingFromRightDown", file="resources/electrified_edge_fRIGHT_pDOWN.png")
electrifiedEdgePointingFromRightUp = Cell(gets = ["right"], gives = ["up"], name = "ElectrifiedEdgePointingFromRightUp", file="resources/electrified_edge_fRIGHT_pUP.png")
electrifiedEdgePointingFromUpLeft = Cell(gets = ["up"], gives = ["left"], name = "ElectrifiedEdgePointingFromUpLeft", file="resources/electrified_edge_fUP_pLEFT.png")
electrifiedEdgePointingFromUpRight = Cell(gets = ["up"], gives = ["right"], name = "ElectrifiedEdgePointingFromUpRight", file="resources/electrified_edge_fUP_pRIGHT.png")

inverter = Cell(gets = [], gives = [], name = "Inverter", file="resources/inverter.png")
electrifiedInverter = Cell(gets = [], gives = ["down", "up", "left", "right"], name = "ElectrifiedInverter", file="resources/electrified_inverter.png")

conveyorPointingUp = Cell(gets = ["C_down", "up", "left", "right"], gives = [], name = "ConveyorPointingUp", file = "resources/conveyor_pUP.png")
conveyorPointingDown = Cell(gets = ["C_up", "down", "left", "right"], gives = [], name = "ConveyorPointingDown", file = "resources/conveyor_pDOWN.png")
conveyorPointingLeft = Cell(gets = ["C_right", "down", "up", "left"], gives = [], name = "ConveyorPointingLeft", file = "resources/conveyor_pLEFT.png")
conveyorPointingRight = Cell(gets = ["C_left", "down", "up", "right"], gives = [], name = "ConveyorPointingRight", file = "resources/conveyor_pRIGHT.png")
electrifiedConveyorPointingUp = Cell(gets = ["up", "right", "left"], gives = [], name = "ElectrifiedConveyorPointingUp", file = "resources/electrified_conveyor_pUP.png")
electrifiedConveyorPointingDown = Cell(gets = ["down", "right", "left"], gives = [], name = "ElectrifiedConveyorPointingDown", file = "resources/electrified_conveyor_pDOWN.png")
electrifiedConveyorPointingLeft = Cell(gets = ["up", "down", "left"], gives = [], name = "ElectrifiedConveyorPointingLeft", file = "resources/electrified_conveyor_pLEFT.png")
electrifiedConveyorPointingRight = Cell(gets = ["up", "right", "down"], gives = [], name = "ElectrifiedConveyorPointingRight", file = "resources/electrified_conveyor_pRIGHT.png")
conveyorPointingUpContainingGenerator = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingGenerator", file = "resources/conveyor_pUP_c(generator).png")
conveyorPointingUpContainingArrowPointingUp = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingArrowPointingUp", file = "resources/conveyor_pUP_c(arrow_pUP).png")
conveyorPointingUpContainingArrowPointingDown = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingArrowPointingDown", file = "resources/conveyor_pUP_c(arrow_pDOWN).png")
conveyorPointingUpContainingArrowPointingLeft = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingArrowPointingLeft", file = "resources/conveyor_pUP_c(arrow_pLEFT).png")
conveyorPointingUpContainingArrowPointingRight = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingArrowPointingRight", file = "resources/conveyor_pUP_c(arrow_pRIGHT).png")
conveyorPointingUpContainingElectrifiedArrowPointingUp = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingElectrifiedArrowPointingUp", file = "resources/conveyor_pUP_c(electrified_arrow_pUP).png")
conveyorPointingUpContainingElectrifiedArrowPointingDown = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingElectrifiedArrowPointingDown", file = "resources/conveyor_pUP_c(electrified_arrow_pDOWN).png")
conveyorPointingUpContainingElectrifiedArrowPointingLeft = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingElectrifiedArrowPointingLeft", file = "resources/conveyor_pUP_c(electrified_arrow_pLEFT).png")
conveyorPointingUpContainingElectrifiedArrowPointingRight = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingElectrifiedArrowPointingRight", file = "resources/conveyor_pUP_c(electrified_arrow_pRIGHT).png")
conveyorPointingUpContainingEdgePointingFromDownLeft = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingEdgePointingFromDownLeft", file = "resources/conveyor_pUP_c(edge_fDOWN_pLEFT).png")
conveyorPointingUpContainingEdgePointingFromDownRight = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingEdgePointingFromDownRight", file = "resources/conveyor_pUP_c(edge_fDOWN_pRIGHT).png")
conveyorPointingUpContainingEdgePointingFromLeftDown = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingEdgePointingFromLeftDown", file = "resources/conveyor_pUP_c(edge_fLEFT_pDOWN).png")
conveyorPointingUpContainingEdgePointingFromLeftUp = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingEdgePointingFromLeftUp", file = "resources/conveyor_pUP_c(edge_fLEFT_pUP).png")
conveyorPointingUpContainingEdgePointingFromRightDown = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingEdgePointingFromRightDown", file = "resources/conveyor_pUP_c(edge_fRIGHT_pDOWN).png")
conveyorPointingUpContainingEdgePointingFromRightUp = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingEdgePointingFromRightUp", file = "resources/conveyor_pUP_c(edge_fRIGHT_pUP).png")
conveyorPointingUpContainingEdgePointingFromUpLeft= Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingEdgePointingFromUpLeft", file = "resources/conveyor_pUP_c(edge_fUP_pLEFT).png")
conveyorPointingUpContainingEdgePointingFromUpRight = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingEdgePointingFromUpRight", file = "resources/conveyor_pUP_c(edge_fUP_pRIGHT).png")
conveyorPointingUpContainingElectrifiedEdgePointingFromDownLeft = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingElectrifiedEdgePointingFromDownLeft", file = "resources/conveyor_pUP_c(electrified_edge_fDOWN_pLEFT).png")
conveyorPointingUpContainingElectrifiedEdgePointingFromDownRight = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingElectrifiedEdgePointingFromDownRight", file = "resources/conveyor_pUP_c(electrified_edge_fDOWN_pRIGHT).png")
conveyorPointingUpContainingElectrifiedEdgePointingFromLeftDown = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingElectrifiedEdgePointingFromLeftDown", file = "resources/conveyor_pUP_c(electrified_edge_fLEFT_pDOWN).png")
conveyorPointingUpContainingElectrifiedEdgePointingFromLeftUp = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingElectrifiedEdgePointingFromLeftUp", file = "resources/conveyor_pUP_c(electrified_edge_fLEFT_pUP).png")
conveyorPointingUpContainingElectrifiedEdgePointingFromRightDown = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingElectrifiedEdgePointingFromRightDown", file = "resources/conveyor_pUP_c(electrified_edge_fRIGHT_pDOWN).png")
conveyorPointingUpContainingElectrifiedEdgePointingFromRightUp = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingElectrifiedEdgePointingFromRightUp", file = "resources/conveyor_pUP_c(electrified_edge_fRIGHT_pUP).png")
conveyorPointingUpContainingElectrifiedEdgePointingFromUpLeft = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingElectrifiedEdgePointingFromUpLeft", file = "resources/conveyor_pUP_c(electrified_edge_fUP_pLEFT).png")
conveyorPointingUpContainingElectrifiedEdgePointingFromUpRight = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingElectrifiedEdgePointingFromUpRight", file = "resources/conveyor_pUP_c(electrified_edge_fUP_pRIGHT).png")
conveyorPointingUpContainingInverter = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingInverter", file = "resources/conveyor_pUP_c(inverter).png")
conveyorPointingUpContainingElectrifiedInverter = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingElectrifiedInverter", file = "resources/conveyor_pUP_c(electrified_inverter).png")
conveyorPointingUpContainingConveyorPointingUp = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingConveyorPointingUp", file = "resources/conveyor_pUP_c(conveyor_pUP).png")
conveyorPointingUpContainingConveyorPointingLeft = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingConveyorPointingLeft", file = "resources/conveyor_pUP_c(conveyor_pLEFT).png")
conveyorPointingUpContainingConveyorPointingDown = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingConveyorPointingDown", file = "resources/conveyor_pUP_c(conveyor_pDOWN).png")
conveyorPointingUpContainingConveyorPointingRight = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingConveyorPointingRight", file = "resources/conveyor_pUP_c(conveyor_pRIGHT).png")
conveyorPointingUpContainingBattery0PercentCharged = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingBattery0PercentCharged", file = "resources/conveyor_pUP_c(battery_0%).png")
conveyorPointingUpContainingBattery25PercentCharged = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingBattery25PercentCharged", file = "resources/conveyor_pUP_c(battery_25%).png")
conveyorPointingUpContainingBattery50PercentCharged = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingBattery50PercentCharged", file = "resources/conveyor_pUP_c(battery_50%).png")
conveyorPointingUpContainingBattery75PercentCharged = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingBattery75PercentCharged", file = "resources/conveyor_pUP_c(battery_75%).png")
conveyorPointingUpContainingBattery100PercentCharged = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingBattery100PercentCharged", file = "resources/conveyor_pUP_c(battery_100%).png")
conveyorPointingUpContainingElectrifiedConveyorPointingUp = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingElectrifiedConveyorPointingUp", file = "resources/conveyor_pUP_c(electrified_conveyor_pUP).png")
conveyorPointingUpContainingElectrifiedConveyorPointingDown = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingElectrifiedConveyorPointingDown", file = "resources/conveyor_pUP_c(electrified_conveyor_pDOWN).png")
conveyorPointingUpContainingElectrifiedConveyorPointingLeft = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingElectrifiedConveyorPointingLeft", file = "resources/conveyor_pUP_c(electrified_conveyor_pLEFT).png")
conveyorPointingUpContainingElectrifiedConveyorPointingRight = Cell(gets = [], gives = ["up"], name = "ConveyorPointingUpContainingElectrifiedConveyorPointingRight", file = "resources/conveyor_pUP_c(electrified_conveyor_pRIGHT).png")
conveyorPointingLeftContainingGenerator = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingGenerator", file = "resources/conveyor_pLEFT_c(generator).png")
conveyorPointingLeftContainingArrowPointingUp = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingArrowPointingUp", file = "resources/conveyor_pLEFT_c(arrow_pUP).png")
conveyorPointingLeftContainingArrowPointingDown = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingArrowPointingDown", file = "resources/conveyor_pLEFT_c(arrow_pDOWN).png")
conveyorPointingLeftContainingArrowPointingLeft = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingArrowPointingLeft", file = "resources/conveyor_pLEFT_c(arrow_pLEFT).png")
conveyorPointingLeftContainingArrowPointingRight = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingArrowPointingRight", file = "resources/conveyor_pLEFT_c(arrow_pRIGHT).png")
conveyorPointingLeftContainingElectrifiedArrowPointingUp = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingElectrifiedArrowPointingUp", file = "resources/conveyor_pLEFT_c(electrified_arrow_pUP).png")
conveyorPointingLeftContainingElectrifiedArrowPointingDown = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingElectrifiedArrowPointingDown", file = "resources/conveyor_pLEFT_c(electrified_arrow_pDOWN).png")
conveyorPointingLeftContainingElectrifiedArrowPointingLeft = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingElectrifiedArrowPointingLeft", file = "resources/conveyor_pLEFT_c(electrified_arrow_pLEFT).png")
conveyorPointingLeftContainingElectrifiedArrowPointingRight = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingElectrifiedArrowPointingRight", file = "resources/conveyor_pLEFT_c(electrified_arrow_pRIGHT).png")
conveyorPointingLeftContainingEdgePointingFromDownLeft = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingEdgePointingFromDownLeft", file = "resources/conveyor_pLEFT_c(edge_fDOWN_pLEFT).png")
conveyorPointingLeftContainingEdgePointingFromDownRight = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingEdgePointingFromDownRight", file = "resources/conveyor_pLEFT_c(edge_fDOWN_pRIGHT).png")
conveyorPointingLeftContainingEdgePointingFromLeftDown = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingEdgePointingFromLeftDown", file = "resources/conveyor_pLEFT_c(edge_fLEFT_pDOWN).png")
conveyorPointingLeftContainingEdgePointingFromLeftUp = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingEdgePointingFromLeftUp", file = "resources/conveyor_pLEFT_c(edge_fLEFT_pUP).png")
conveyorPointingLeftContainingEdgePointingFromRightDown = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingEdgePointingFromRightDown", file = "resources/conveyor_pLEFT_c(edge_fRIGHT_pDOWN).png")
conveyorPointingLeftContainingEdgePointingFromRightUp = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingEdgePointingFromRightUp", file = "resources/conveyor_pLEFT_c(edge_fRIGHT_pUP).png")
conveyorPointingLeftContainingEdgePointingFromUpLeft= Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingEdgePointingFromUpLeft", file = "resources/conveyor_pLEFT_c(edge_fUP_pLEFT).png")
conveyorPointingLeftContainingEdgePointingFromUpRight = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingEdgePointingFromUpRight", file = "resources/conveyor_pLEFT_c(edge_fUP_pRIGHT).png")
conveyorPointingLeftContainingElectrifiedEdgePointingFromDownLeft = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingElectrifiedEdgePointingFromDownLeft", file = "resources/conveyor_pLEFT_c(electrified_edge_fDOWN_pLEFT).png")
conveyorPointingLeftContainingElectrifiedEdgePointingFromDownRight = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingElectrifiedEdgePointingFromDownRight", file = "resources/conveyor_pLEFT_c(electrified_edge_fDOWN_pRIGHT).png")
conveyorPointingLeftContainingElectrifiedEdgePointingFromLeftDown = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingElectrifiedEdgePointingFromLeftDown", file = "resources/conveyor_pLEFT_c(electrified_edge_fLEFT_pDOWN).png")
conveyorPointingLeftContainingElectrifiedEdgePointingFromLeftUp = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingElectrifiedEdgePointingFromLeftUp", file = "resources/conveyor_pLEFT_c(electrified_edge_fLEFT_pUP).png")
conveyorPointingLeftContainingElectrifiedEdgePointingFromRightDown = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingElectrifiedEdgePointingFromRightDown", file = "resources/conveyor_pLEFT_c(electrified_edge_fRIGHT_pDOWN).png")
conveyorPointingLeftContainingElectrifiedEdgePointingFromRightUp = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingElectrifiedEdgePointingFromRightUp", file = "resources/conveyor_pLEFT_c(electrified_edge_fRIGHT_pUP).png")
conveyorPointingLeftContainingElectrifiedEdgePointingFromUpLeft = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingElectrifiedEdgePointingFromUpLeft", file = "resources/conveyor_pLEFT_c(electrified_edge_fUP_pLEFT).png")
conveyorPointingLeftContainingElectrifiedEdgePointingFromUpRight = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingElectrifiedEdgePointingFromUpRight", file = "resources/conveyor_pLEFT_c(electrified_edge_fUP_pRIGHT).png")
conveyorPointingLeftContainingInverter = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingInverter", file = "resources/conveyor_pLEFT_c(inverter).png")
conveyorPointingLeftContainingElectrifiedInverter = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingElectrifiedInverter", file = "resources/conveyor_pLEFT_c(electrified_inverter).png")
conveyorPointingLeftContainingConveyorPointingUp = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingConveyorPointingUp", file = "resources/conveyor_pLEFT_c(conveyor_pUP).png")
conveyorPointingLeftContainingConveyorPointingLeft = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingConveyorPointingLeft", file = "resources/conveyor_pLEFT_c(conveyor_pLEFT).png")
conveyorPointingLeftContainingConveyorPointingDown = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingConveyorPointingDown", file = "resources/conveyor_pLEFT_c(conveyor_pDOWN).png")
conveyorPointingLeftContainingConveyorPointingRight = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingConveyorPointingRight", file = "resources/conveyor_pLEFT_c(conveyor_pRIGHT).png")
conveyorPointingLeftContainingBattery0PercentCharged = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingBattery0PercentCharged", file = "resources/conveyor_pLEFT_c(battery_0%).png")
conveyorPointingLeftContainingBattery25PercentCharged = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingBattery25PercentCharged", file = "resources/conveyor_pLEFT_c(battery_25%).png")
conveyorPointingLeftContainingBattery50PercentCharged = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingBattery50PercentCharged", file = "resources/conveyor_pLEFT_c(battery_50%).png")
conveyorPointingLeftContainingBattery75PercentCharged = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingBattery75PercentCharged", file = "resources/conveyor_pLEFT_c(battery_75%).png")
conveyorPointingLeftContainingBattery100PercentCharged = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingBattery100PercentCharged", file = "resources/conveyor_pLEFT_c(battery_100%).png")
conveyorPointingLeftContainingElectrifiedConveyorPointingUp = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingElectrifiedConveyorPointingUp", file = "resources/conveyor_pLEFT_c(electrified_conveyor_pUP).png")
conveyorPointingLeftContainingElectrifiedConveyorPointingDown = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingElectrifiedConveyorPointingDown", file = "resources/conveyor_pLEFT_c(electrified_conveyor_pDOWN).png")
conveyorPointingLeftContainingElectrifiedConveyorPointingLeft = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingElectrifiedConveyorPointingLeft", file = "resources/conveyor_pLEFT_c(electrified_conveyor_pLEFT).png")
conveyorPointingLeftContainingElectrifiedConveyorPointingRight = Cell(gets = [], gives = ["left"], name = "ConveyorPointingLeftContainingElectrifiedConveyorPointingRight", file = "resources/conveyor_pLEFT_c(electrified_conveyor_pRIGHT).png")
conveyorPointingRightContainingGenerator = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingGenerator", file = "resources/conveyor_pRIGHT_c(generator).png")
conveyorPointingRightContainingArrowPointingUp = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingArrowPointingUp", file = "resources/conveyor_pRIGHT_c(arrow_pUP).png")
conveyorPointingRightContainingArrowPointingDown = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingArrowPointingDown", file = "resources/conveyor_pRIGHT_c(arrow_pDOWN).png")
conveyorPointingRightContainingArrowPointingLeft = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingArrowPointingLeft", file = "resources/conveyor_pRIGHT_c(arrow_pLEFT).png")
conveyorPointingRightContainingArrowPointingRight = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingArrowPointingRight", file = "resources/conveyor_pRIGHT_c(arrow_pRIGHT).png")
conveyorPointingRightContainingElectrifiedArrowPointingUp = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingElectrifiedArrowPointingUp", file = "resources/conveyor_pRIGHT_c(electrified_arrow_pUP).png")
conveyorPointingRightContainingElectrifiedArrowPointingDown = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingElectrifiedArrowPointingDown", file = "resources/conveyor_pRIGHT_c(electrified_arrow_pDOWN).png")
conveyorPointingRightContainingElectrifiedArrowPointingLeft = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingElectrifiedArrowPointingLeft", file = "resources/conveyor_pRIGHT_c(electrified_arrow_pLEFT).png")
conveyorPointingRightContainingElectrifiedArrowPointingRight = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingElectrifiedArrowPointingRight", file = "resources/conveyor_pRIGHT_c(electrified_arrow_pRIGHT).png")
conveyorPointingRightContainingEdgePointingFromDownLeft = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingEdgePointingFromDownLeft", file = "resources/conveyor_pRIGHT_c(edge_fDOWN_pLEFT).png")
conveyorPointingRightContainingEdgePointingFromDownRight = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingEdgePointingFromDownRight", file = "resources/conveyor_pRIGHT_c(edge_fDOWN_pRIGHT).png")
conveyorPointingRightContainingEdgePointingFromLeftDown = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingEdgePointingFromLeftDown", file = "resources/conveyor_pRIGHT_c(edge_fLEFT_pDOWN).png")
conveyorPointingRightContainingEdgePointingFromLeftUp = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingEdgePointingFromLeftUp", file = "resources/conveyor_pRIGHT_c(edge_fLEFT_pUP).png")
conveyorPointingRightContainingEdgePointingFromRightDown = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingEdgePointingFromRightDown", file = "resources/conveyor_pRIGHT_c(edge_fRIGHT_pDOWN).png")
conveyorPointingRightContainingEdgePointingFromRightUp = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingEdgePointingFromRightUp", file = "resources/conveyor_pRIGHT_c(edge_fRIGHT_pUP).png")
conveyorPointingRightContainingEdgePointingFromUpLeft= Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingEdgePointingFromUpLeft", file = "resources/conveyor_pRIGHT_c(edge_fUP_pLEFT).png")
conveyorPointingRightContainingEdgePointingFromUpRight = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingEdgePointingFromUpRight", file = "resources/conveyor_pRIGHT_c(edge_fUP_pRIGHT).png")
conveyorPointingRightContainingElectrifiedEdgePointingFromDownLeft = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingElectrifiedEdgePointingFromDownLeft", file = "resources/conveyor_pRIGHT_c(electrified_edge_fDOWN_pLEFT).png")
conveyorPointingRightContainingElectrifiedEdgePointingFromDownRight = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingElectrifiedEdgePointingFromDownRight", file = "resources/conveyor_pRIGHT_c(electrified_edge_fDOWN_pRIGHT).png")
conveyorPointingRightContainingElectrifiedEdgePointingFromLeftDown = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingElectrifiedEdgePointingFromLeftDown", file = "resources/conveyor_pRIGHT_c(electrified_edge_fLEFT_pDOWN).png")
conveyorPointingRightContainingElectrifiedEdgePointingFromLeftUp = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingElectrifiedEdgePointingFromLeftUp", file = "resources/conveyor_pRIGHT_c(electrified_edge_fLEFT_pUP).png")
conveyorPointingRightContainingElectrifiedEdgePointingFromRightDown = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingElectrifiedEdgePointingFromRightDown", file = "resources/conveyor_pRIGHT_c(electrified_edge_fRIGHT_pDOWN).png")
conveyorPointingRightContainingElectrifiedEdgePointingFromRightUp = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingElectrifiedEdgePointingFromRightUp", file = "resources/conveyor_pRIGHT_c(electrified_edge_fRIGHT_pUP).png")
conveyorPointingRightContainingElectrifiedEdgePointingFromUpLeft = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingElectrifiedEdgePointingFromUpLeft", file = "resources/conveyor_pRIGHT_c(electrified_edge_fUP_pLEFT).png")
conveyorPointingRightContainingElectrifiedEdgePointingFromUpRight = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingElectrifiedEdgePointingFromUpRight", file = "resources/conveyor_pRIGHT_c(electrified_edge_fUP_pRIGHT).png")
conveyorPointingRightContainingInverter = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingInverter", file = "resources/conveyor_pRIGHT_c(inverter).png")
conveyorPointingRightContainingElectrifiedInverter = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingElectrifiedInverter", file = "resources/conveyor_pRIGHT_c(electrified_inverter).png")
conveyorPointingRightContainingConveyorPointingUp = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingConveyorPointingUp", file = "resources/conveyor_pRIGHT_c(conveyor_pUP).png")
conveyorPointingRightContainingConveyorPointingLeft = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingConveyorPointingLeft", file = "resources/conveyor_pRIGHT_c(conveyor_pLEFT).png")
conveyorPointingRightContainingConveyorPointingDown = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingConveyorPointingDown", file = "resources/conveyor_pRIGHT_c(conveyor_pDOWN).png")
conveyorPointingRightContainingConveyorPointingRight = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingConveyorPointingRight", file = "resources/conveyor_pRIGHT_c(conveyor_pRIGHT).png")
conveyorPointingRightContainingBattery0PercentCharged = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingBattery0PercentCharged", file = "resources/conveyor_pRIGHT_c(battery_0%).png")
conveyorPointingRightContainingBattery25PercentCharged = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingBattery25PercentCharged", file = "resources/conveyor_pRIGHT_c(battery_25%).png")
conveyorPointingRightContainingBattery50PercentCharged = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingBattery50PercentCharged", file = "resources/conveyor_pRIGHT_c(battery_50%).png")
conveyorPointingRightContainingBattery75PercentCharged = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingBattery75PercentCharged", file = "resources/conveyor_pRIGHT_c(battery_75%).png")
conveyorPointingRightContainingBattery100PercentCharged = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingBattery100PercentCharged", file = "resources/conveyor_pRIGHT_c(battery_100%).png")
conveyorPointingRightContainingElectrifiedConveyorPointingUp = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingElectrifiedConveyorPointingUp", file = "resources/conveyor_pRIGHT_c(electrified_conveyor_pUP).png")
conveyorPointingRightContainingElectrifiedConveyorPointingDown = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingElectrifiedConveyorPointingDown", file = "resources/conveyor_pRIGHT_c(electrified_conveyor_pDOWN).png")
conveyorPointingRightContainingElectrifiedConveyorPointingLeft = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingElectrifiedConveyorPointingLeft", file = "resources/conveyor_pRIGHT_c(electrified_conveyor_pLEFT).png")
conveyorPointingRightContainingElectrifiedConveyorPointingRight = Cell(gets = [], gives = ["right"], name = "ConveyorPointingRightContainingElectrifiedConveyorPointingRight", file = "resources/conveyor_pRIGHT_c(electrified_conveyor_pRIGHT).png")
conveyorPointingDownContainingGenerator = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingGenerator", file = "resources/conveyor_pDOWN_c(generator).png")
conveyorPointingDownContainingArrowPointingUp = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingArrowPointingUp", file = "resources/conveyor_pDOWN_c(arrow_pUP).png")
conveyorPointingDownContainingArrowPointingDown = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingArrowPointingDown", file = "resources/conveyor_pDOWN_c(arrow_pDOWN).png")
conveyorPointingDownContainingArrowPointingLeft = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingArrowPointingLeft", file = "resources/conveyor_pDOWN_c(arrow_pLEFT).png")
conveyorPointingDownContainingArrowPointingRight = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingArrowPointingRight", file = "resources/conveyor_pDOWN_c(arrow_pRIGHT).png")
conveyorPointingDownContainingElectrifiedArrowPointingUp = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingElectrifiedArrowPointingUp", file = "resources/conveyor_pDOWN_c(electrified_arrow_pUP).png")
conveyorPointingDownContainingElectrifiedArrowPointingDown = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingElectrifiedArrowPointingDown", file = "resources/conveyor_pDOWN_c(electrified_arrow_pDOWN).png")
conveyorPointingDownContainingElectrifiedArrowPointingLeft = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingElectrifiedArrowPointingLeft", file = "resources/conveyor_pDOWN_c(electrified_arrow_pLEFT).png")
conveyorPointingDownContainingElectrifiedArrowPointingRight = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingElectrifiedArrowPointingRight", file = "resources/conveyor_pDOWN_c(electrified_arrow_pRIGHT).png")
conveyorPointingDownContainingEdgePointingFromDownLeft = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingEdgePointingFromDownLeft", file = "resources/conveyor_pDOWN_c(edge_fDOWN_pLEFT).png")
conveyorPointingDownContainingEdgePointingFromDownRight = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingEdgePointingFromDownRight", file = "resources/conveyor_pDOWN_c(edge_fDOWN_pRIGHT).png")
conveyorPointingDownContainingEdgePointingFromLeftDown = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingEdgePointingFromLeftDown", file = "resources/conveyor_pDOWN_c(edge_fLEFT_pDOWN).png")
conveyorPointingDownContainingEdgePointingFromLeftUp = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingEdgePointingFromLeftUp", file = "resources/conveyor_pDOWN_c(edge_fLEFT_pUP).png")
conveyorPointingDownContainingEdgePointingFromRightDown = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingEdgePointingFromRightDown", file = "resources/conveyor_pDOWN_c(edge_fRIGHT_pDOWN).png")
conveyorPointingDownContainingEdgePointingFromRightUp = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingEdgePointingFromRightUp", file = "resources/conveyor_pDOWN_c(edge_fRIGHT_pUP).png")
conveyorPointingDownContainingEdgePointingFromUpLeft= Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingEdgePointingFromUpLeft", file = "resources/conveyor_pDOWN_c(edge_fUP_pLEFT).png")
conveyorPointingDownContainingEdgePointingFromUpRight = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingEdgePointingFromUpRight", file = "resources/conveyor_pDOWN_c(edge_fUP_pRIGHT).png")
conveyorPointingDownContainingElectrifiedEdgePointingFromDownLeft = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingElectrifiedEdgePointingFromDownLeft", file = "resources/conveyor_pDOWN_c(electrified_edge_fDOWN_pLEFT).png")
conveyorPointingDownContainingElectrifiedEdgePointingFromDownRight = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingElectrifiedEdgePointingFromDownRight", file = "resources/conveyor_pDOWN_c(electrified_edge_fDOWN_pRIGHT).png")
conveyorPointingDownContainingElectrifiedEdgePointingFromLeftDown = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingElectrifiedEdgePointingFromLeftDown", file = "resources/conveyor_pDOWN_c(electrified_edge_fLEFT_pDOWN).png")
conveyorPointingDownContainingElectrifiedEdgePointingFromLeftUp = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingElectrifiedEdgePointingFromLeftUp", file = "resources/conveyor_pDOWN_c(electrified_edge_fLEFT_pUP).png")
conveyorPointingDownContainingElectrifiedEdgePointingFromRightDown = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingElectrifiedEdgePointingFromRightDown", file = "resources/conveyor_pDOWN_c(electrified_edge_fRIGHT_pDOWN).png")
conveyorPointingDownContainingElectrifiedEdgePointingFromRightUp = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingElectrifiedEdgePointingFromRightUp", file = "resources/conveyor_pDOWN_c(electrified_edge_fRIGHT_pUP).png")
conveyorPointingDownContainingElectrifiedEdgePointingFromUpLeft = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingElectrifiedEdgePointingFromUpLeft", file = "resources/conveyor_pDOWN_c(electrified_edge_fUP_pLEFT).png")
conveyorPointingDownContainingElectrifiedEdgePointingFromUpRight = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingElectrifiedEdgePointingFromUpRight", file = "resources/conveyor_pDOWN_c(electrified_edge_fUP_pRIGHT).png")
conveyorPointingDownContainingInverter = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingInverter", file = "resources/conveyor_pDOWN_c(inverter).png")
conveyorPointingDownContainingElectrifiedInverter = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingElectrifiedInverter", file = "resources/conveyor_pDOWN_c(electrified_inverter).png")
conveyorPointingDownContainingConveyorPointingUp = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingConveyorPointingUp", file = "resources/conveyor_pDOWN_c(conveyor_pUP).png")
conveyorPointingDownContainingConveyorPointingLeft = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingConveyorPointingLeft", file = "resources/conveyor_pDOWN_c(conveyor_pLEFT).png")
conveyorPointingDownContainingConveyorPointingDown = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingConveyorPointingDown", file = "resources/conveyor_pDOWN_c(conveyor_pDOWN).png")
conveyorPointingDownContainingConveyorPointingRight = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingConveyorPointingRight", file = "resources/conveyor_pDOWN_c(conveyor_pRIGHT).png")
conveyorPointingDownContainingBattery0PercentCharged = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingBattery0PercentCharged", file = "resources/conveyor_pDOWN_c(battery_0%).png")
conveyorPointingDownContainingBattery25PercentCharged = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingBattery25PercentCharged", file = "resources/conveyor_pDOWN_c(battery_25%).png")
conveyorPointingDownContainingBattery50PercentCharged = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingBattery50PercentCharged", file = "resources/conveyor_pDOWN_c(battery_50%).png")
conveyorPointingDownContainingBattery75PercentCharged = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingBattery75PercentCharged", file = "resources/conveyor_pDOWN_c(battery_75%).png")
conveyorPointingDownContainingBattery100PercentCharged = Cell(gets = [], gives = ["down"], name = "ConveyorPointingDownContainingBattery100PercentCharged", file = "resources/conveyor_pDOWN_c(battery_100%).png")
conveyorPointingDownContainingElectrifiedConveyorPointingUp = Cell(gets = [], gives = ["up"], name = "ConveyorPointingDownContainingElectrifiedConveyorPointingUp", file = "resources/conveyor_pDOWN_c(electrified_conveyor_pUP).png")
conveyorPointingDownContainingElectrifiedConveyorPointingDown = Cell(gets = [], gives = ["up"], name = "ConveyorPointingDownContainingElectrifiedConveyorPointingDown", file = "resources/conveyor_pDOWN_c(electrified_conveyor_pDOWN).png")
conveyorPointingDownContainingElectrifiedConveyorPointingLeft = Cell(gets = [], gives = ["up"], name = "ConveyorPointingDownContainingElectrifiedConveyorPointingLeft", file = "resources/conveyor_pDOWN_c(electrified_conveyor_pLEFT).png")
conveyorPointingDownContainingElectrifiedConveyorPointingRight = Cell(gets = [], gives = ["up"], name = "ConveyorPointingDownContainingElectrifiedConveyorPointingRight", file = "resources/conveyor_pDOWN_c(electrified_conveyor_pRIGHT).png")

battery0PercentCharged = Cell(gets = ["down", "up", "left", "right"], gives = [], name = "Battery0PercentCharged", file = "resources/battery_0%.png")
battery25PercentCharged = Cell(gets = ["down", "up", "left", "right"], gives = ["down", "up", "left", "right"], name = "Battery25PercentCharged", file = "resources/battery_25%.png")
battery50PercentCharged = Cell(gets = ["down", "up", "left", "right"], gives = ["down", "up", "left", "right"], name = "Battery50PercentCharged", file = "resources/battery_50%.png")
battery75PercentCharged = Cell(gets = ["down", "up", "left", "right"], gives = ["down", "up", "left", "right"], name = "Battery75PercentCharged", file = "resources/battery_75%.png")
battery100PercentCharged = Cell(gets = [], gives = ["down", "up", "left", "right"], name = "Battery100PercentCharged", file = "resources/battery_100%.png")

#MENU ICONS
menuIconArrow = PhotoImage(file="resources/arrow_menu_icon.png")
menuIconGenerator = PhotoImage(file="resources/generator_menu_icon.png")
menuIconEraser = PhotoImage(file="resources/eraser_menu_icon.png")
menuIconConfigurator = PhotoImage(file="resources/configurator_menu_icon.png")
menuIconEdge = PhotoImage(file="resources/edge_menu_icon.png")
menuIconInverter = PhotoImage(file="resources/inverter_menu_icon.png")
menuIconConveyor = PhotoImage(file="resources/conveyor_menu_icon.png")
menuIconBattery = PhotoImage(file="resources/battery_menu_icon.png")

#UTILITIES
pauseImage = PhotoImage(file="resources/pause_image.png")