from tkinter import *

class Cell(PhotoImage):
    def __init__(self, gets, gives, name, file, deleted = False):
        PhotoImage.__init__(self, file=file, name=name)
        self.gets = gets
        self.gives = gives
        self.deleted = deleted

tk = Tk()

#ICON
appIcon = PhotoImage(file="resources/arrow_circuits_icon.ico")

#CELLS
emptyCell = Cell(gets = None, gives = None, name="EmptyCell", file="resources/empty_cell.png")
generator = Cell(gets = None, gives = None, name="Generator", file="resources/generator.png")

arrowPointingUp = Cell(gets = "down", gives = "up", name ="ArrowPointingUp", file="resources/arrow_pUP.png")
arrowPointingDown = Cell(gets = "up", gives = "down", name ="ArrowPointingDown", file="resources/arrow_pDOWN.png")
arrowPointingLeft = Cell(gets = "right", gives = "left", name ="ArrowPointingLeft", file="resources/arrow_pLEFT.png")
arrowPointingRight = Cell(gets = "left", gives = "right", name ="ArrowPointingRight", file="resources/arrow_pRIGHT.png")
electrifiedArrowPointingUp = Cell(gets = "down", gives = "up", name = "ElectrifiedArrowPointingUp", file="resources/electrified_arrow_pUP.png")
electrifiedArrowPointingDown = Cell(gets = "up", gives = "down", name = "ElectrifiedArrowPointingDown", file="resources/electrified_arrow_pDOWN.png")
electrifiedArrowPointingLeft = Cell(gets = "right", gives = "left", name = "ElectrifiedArrowPointingLeft", file="resources/electrified_arrow_pLEFT.png")
electrifiedArrowPointingRight = Cell(gets = "left", gives = "right", name = "ElectrifiedArrowPointingRight", file="resources/electrified_arrow_pRIGHT.png")

edgePointingFromDownLeft = Cell(gets = "down", gives = "left", name = "EdgePointingFromDownLeft", file="resources/edge_fDOWN_pLEFT.png")
edgePointingFromDownRight = Cell(gets = "down", gives = "right", name = "EdgePointingFromDownRight", file="resources/edge_fDOWN_pRIGHT.png")
edgePointingFromLeftDown = Cell(gets = "left", gives = "down", name = "EdgePointingFromLeftDown", file="resources/edge_fLEFT_pDOWN.png")
edgePointingFromLeftUp = Cell(gets = "left", gives = "up", name = "EdgePointingFromLeftUp", file="resources/edge_fLEFT_pUP.png")
edgePointingFromRightDown = Cell(gets = "right", gives = "down", name = "EdgePointingFromRightDown", file="resources/edge_fRIGHT_pDOWN.png")
edgePointingFromRightUp = Cell(gets = "right", gives = "up", name = "EdgePointingFromRightUp", file="resources/edge_fRIGHT_pUP.png")
edgePointingFromUpLeft = Cell(gets = "up", gives = "left", name = "EdgePointingFromUpLeft", file="resources/edge_fUP_pLEFT.png")
edgePointingFromUpRight = Cell(gets = "up", gives = "right", name = "EdgePointingFromUpRight", file="resources/edge_fUP_pRIGHT.png")
electrifiedEdgePointingFromDownLeft = Cell(gets = "down", gives = "left", name = "ElectrifiedEdgePointingFromDownLeft", file="resources/electrified_edge_fDOWN_pLEFT.png")
electrifiedEdgePointingFromDownRight = Cell(gets = "down", gives = "right", name = "ElectrifiedEdgePointingFromDownRight", file="resources/electrified_edge_fDOWN_pRIGHT.png")
electrifiedEdgePointingFromLeftDown = Cell(gets = "left", gives = "down", name = "ElectrifiedEdgePointingFromLeftDown", file="resources/electrified_edge_fLEFT_pDOWN.png")
electrifiedEdgePointingFromLeftUp = Cell(gets = "left", gives = "up", name = "ElectrifiedEdgePointingFromLeftUp", file="resources/electrified_edge_fLEFT_pUP.png")
electrifiedEdgePointingFromRightDown = Cell(gets = "right", gives = "down", name = "ElectrifiedEdgePointingFromRightDown", file="resources/electrified_edge_fRIGHT_pDOWN.png")
electrifiedEdgePointingFromRightUp = Cell(gets = "right", gives = "up", name = "ElectrifiedEdgePointingFromRightUp", file="resources/electrified_edge_fRIGHT_pUP.png")
electrifiedEdgePointingFromUpLeft = Cell(gets = "up", gives = "left", name = "ElectrifiedEdgePointingFromUpLeft", file="resources/electrified_edge_fUP_pLEFT.png")
electrifiedEdgePointingFromUpRight = Cell(gets = "up", gives = "right", name = "ElectrifiedEdgePointingFromUpRight", file="resources/electrified_edge_fUP_pRIGHT.png")

inverter = Cell(gets = None, gives = None, name = "Inverter", file="resources/inverter.png")
electrifiedInverter = Cell(gets = None, gives = None, name = "ElectrifiedInverter", file="resources/electrified_inverter.png")

conveyorPointingUp = Cell(gets = "down", gives = "up", name = "ConveyorPointingUp", file = "resources/conveyor_pUP.png")
conveyorPointingLeft = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeft", file = "resources/conveyor_pLEFT.png")
conveyorPointingDown = Cell(gets = "up", gives = "down", name = "ConveyorPointingDown", file = "resources/conveyor_pDOWN.png")
conveyorPointingRight = Cell(gets = "left", gives = "right", name = "ConveyorPointingRight", file = "resources/conveyor_pRIGHT.png")

conveyorPointingUpContainingGenerator = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingGenerator", file = "resources/conveyor_pUP_c(generator).png")
conveyorPointingUpContainingArrowPointingUp = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingArrowPointingUp", file = "resources/conveyor_pUP_c(arrow_pUP).png")
conveyorPointingUpContainingArrowPointingDown = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingArrowPointingDown", file = "resources/conveyor_pUP_c(arrow_pDOWN).png")
conveyorPointingUpContainingArrowPointingLeft = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingArrowPointingLeft", file = "resources/conveyor_pUP_c(arrow_pLEFT).png")
conveyorPointingUpContainingArrowPointingRight = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingArrowPointingRight", file = "resources/conveyor_pUP_c(arrow_pRIGHT).png")
conveyorPointingUpContainingElectrifiedArrowPointingUp = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingElectrifiedArrowPointingUp", file = "resources/conveyor_pUP_c(electrified_arrow_pUP).png")
conveyorPointingUpContainingElectrifiedArrowPointingDown = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingElectrifiedArrowPointingDown", file = "resources/conveyor_pUP_c(electrified_arrow_pDOWN).png")
conveyorPointingUpContainingElectrifiedArrowPointingLeft = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingElectrifiedArrowPointingLeft", file = "resources/conveyor_pUP_c(electrified_arrow_pLEFT).png")
conveyorPointingUpContainingElectrifiedArrowPointingRight = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingElectrifiedArrowPointingRight", file = "resources/conveyor_pUP_c(electrified_arrow_pRIGHT).png")
conveyorPointingUpContainingEdgePointingFromDownLeft = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingEdgePointingFromDownLeft", file = "resources/conveyor_pUP_c(edge_fDOWN_pLEFT).png")
conveyorPointingUpContainingEdgePointingFromDownRight = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingEdgePointingFromDownRight", file = "resources/conveyor_pUP_c(edge_fDOWN_pRIGHT).png")
conveyorPointingUpContainingEdgePointingFromLeftDown = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingEdgePointingFromLeftDown", file = "resources/conveyor_pUP_c(edge_fLEFT_pDOWN).png")
conveyorPointingUpContainingEdgePointingFromLeftUp = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingEdgePointingFromLeftUp", file = "resources/conveyor_pUP_c(edge_fLEFT_pUP).png")
conveyorPointingUpContainingEdgePointingFromRightDown = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingEdgePointingFromRightDown", file = "resources/conveyor_pUP_c(edge_fRIGHT_pDOWN).png")
conveyorPointingUpContainingEdgePointingFromRightUp = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingEdgePointingFromRightUp", file = "resources/conveyor_pUP_c(edge_fRIGHT_pUP).png")
conveyorPointingUpContainingEdgePointingFromUpLeft= Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingEdgePointingFromUpLeft", file = "resources/conveyor_pUP_c(edge_fUP_pLEFT).png")
conveyorPointingUpContainingEdgePointingFromUpRight = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingEdgePointingFromUpRight", file = "resources/conveyor_pUP_c(edge_fUP_pRIGHT).png")
conveyorPointingUpContainingElectrifiedEdgePointingFromDownLeft = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingElectrifiedEdgePointingFromDownLeft", file = "resources/conveyor_pUP_c(electrified_edge_fDOWN_pLEFT).png")
conveyorPointingUpContainingElectrifiedEdgePointingFromDownRight = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingElectrifiedEdgePointingFromDownRight", file = "resources/conveyor_pUP_c(electrified_edge_fDOWN_pRIGHT).png")
conveyorPointingUpContainingElectrifiedEdgePointingFromLeftDown = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingElectrifiedEdgePointingFromLeftDown", file = "resources/conveyor_pUP_c(electrified_edge_fLEFT_pDOWN).png")
conveyorPointingUpContainingElectrifiedEdgePointingFromLeftUp = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingElectrifiedEdgePointingFromLeftUp", file = "resources/conveyor_pUP_c(electrified_edge_fLEFT_pUP).png")
conveyorPointingUpContainingElectrifiedEdgePointingFromRightDown = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingElectrifiedEdgePointingFromRightDown", file = "resources/conveyor_pUP_c(electrified_edge_fRIGHT_pDOWN).png")
conveyorPointingUpContainingElectrifiedEdgePointingFromRightUp = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingElectrifiedEdgePointingFromRightUp", file = "resources/conveyor_pUP_c(electrified_edge_fRIGHT_pUP).png")
conveyorPointingUpContainingElectrifiedEdgePointingFromUpLeft = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingElectrifiedEdgePointingFromUpLeft", file = "resources/conveyor_pUP_c(electrified_edge_fUP_pLEFT).png")
conveyorPointingUpContainingElectrifiedEdgePointingFromUpRight = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingElectrifiedEdgePointingFromUpRight", file = "resources/conveyor_pUP_c(electrified_edge_fUP_pRIGHT).png")
conveyorPointingUpContainingInverter = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingInverter", file = "resources/conveyor_pUP_c(inverter).png")
conveyorPointingUpContainingElectrifiedInverter = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingElectrifiedInverter", file = "resources/conveyor_pUP_c(electrified_inverter).png")
conveyorPointingUpContainingConveyorPointingUp = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingConveyorPointingUp", file = "resources/conveyor_pUP_c(conveyor_pUP).png")
conveyorPointingUpContainingConveyorPointingLeft = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingConveyorPointingLeft", file = "resources/conveyor_pUP_c(conveyor_pLEFT).png")
conveyorPointingUpContainingConveyorPointingDown = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingConveyorPointingDown", file = "resources/conveyor_pUP_c(conveyor_pDOWN).png")
conveyorPointingUpContainingConveyorPointingRight = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingConveyorPointingRight", file = "resources/conveyor_pUP_c(conveyor_pRIGHT).png")
conveyorPointingUpContainingBattery0PercentCharged = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingBattery0PercentCharged", file = "resources/conveyor_pUP_c(battery_0%).png")
conveyorPointingUpContainingBattery50PercentCharged = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingBattery50PercentCharged", file = "resources/conveyor_pUP_c(battery_50%).png")
conveyorPointingUpContainingBattery100PercentCharged = Cell(gets = "down", gives = "up", name = "ConveyorPointingUpContainingBattery100PercentCharged", file = "resources/conveyor_pUP_c(battery_100%).png")

conveyorPointingLeftContainingGenerator = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingGenerator", file = "resources/conveyor_pLEFT_c(generator).png")
conveyorPointingLeftContainingArrowPointingUp = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingArrowPointingUp", file = "resources/conveyor_pLEFT_c(arrow_pUP).png")
conveyorPointingLeftContainingArrowPointingDown = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingArrowPointingDown", file = "resources/conveyor_pLEFT_c(arrow_pDOWN).png")
conveyorPointingLeftContainingArrowPointingLeft = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingArrowPointingLeft", file = "resources/conveyor_pLEFT_c(arrow_pLEFT).png")
conveyorPointingLeftContainingArrowPointingRight = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingArrowPointingRight", file = "resources/conveyor_pLEFT_c(arrow_pRIGHT).png")
conveyorPointingLeftContainingElectrifiedArrowPointingUp = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingElectrifiedArrowPointingUp", file = "resources/conveyor_pLEFT_c(electrified_arrow_pUP).png")
conveyorPointingLeftContainingElectrifiedArrowPointingDown = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingElectrifiedArrowPointingDown", file = "resources/conveyor_pLEFT_c(electrified_arrow_pDOWN).png")
conveyorPointingLeftContainingElectrifiedArrowPointingLeft = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingElectrifiedArrowPointingLeft", file = "resources/conveyor_pLEFT_c(electrified_arrow_pLEFT).png")
conveyorPointingLeftContainingElectrifiedArrowPointingRight = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingElectrifiedArrowPointingRight", file = "resources/conveyor_pLEFT_c(electrified_arrow_pRIGHT).png")
conveyorPointingLeftContainingEdgePointingFromDownLeft = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingEdgePointingFromDownLeft", file = "resources/conveyor_pLEFT_c(edge_fDOWN_pLEFT).png")
conveyorPointingLeftContainingEdgePointingFromDownRight = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingEdgePointingFromDownRight", file = "resources/conveyor_pLEFT_c(edge_fDOWN_pRIGHT).png")
conveyorPointingLeftContainingEdgePointingFromLeftDown = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingEdgePointingFromLeftDown", file = "resources/conveyor_pLEFT_c(edge_fLEFT_pDOWN).png")
conveyorPointingLeftContainingEdgePointingFromLeftUp = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingEdgePointingFromLeftUp", file = "resources/conveyor_pLEFT_c(edge_fLEFT_pUP).png")
conveyorPointingLeftContainingEdgePointingFromRightDown = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingEdgePointingFromRightDown", file = "resources/conveyor_pLEFT_c(edge_fRIGHT_pDOWN).png")
conveyorPointingLeftContainingEdgePointingFromRightUp = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingEdgePointingFromRightUp", file = "resources/conveyor_pLEFT_c(edge_fRIGHT_pUP).png")
conveyorPointingLeftContainingEdgePointingFromUpLeft= Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingEdgePointingFromUpLeft", file = "resources/conveyor_pLEFT_c(edge_fUP_pLEFT).png")
conveyorPointingLeftContainingEdgePointingFromUpRight = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingEdgePointingFromUpRight", file = "resources/conveyor_pLEFT_c(edge_fUP_pRIGHT).png")
conveyorPointingLeftContainingElectrifiedEdgePointingFromDownLeft = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingElectrifiedEdgePointingFromDownLeft", file = "resources/conveyor_pLEFT_c(electrified_edge_fDOWN_pLEFT).png")
conveyorPointingLeftContainingElectrifiedEdgePointingFromDownRight = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingElectrifiedEdgePointingFromDownRight", file = "resources/conveyor_pLEFT_c(electrified_edge_fDOWN_pRIGHT).png")
conveyorPointingLeftContainingElectrifiedEdgePointingFromLeftDown = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingElectrifiedEdgePointingFromLeftDown", file = "resources/conveyor_pLEFT_c(electrified_edge_fLEFT_pDOWN).png")
conveyorPointingLeftContainingElectrifiedEdgePointingFromLeftUp = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingElectrifiedEdgePointingFromLeftUp", file = "resources/conveyor_pLEFT_c(electrified_edge_fLEFT_pUP).png")
conveyorPointingLeftContainingElectrifiedEdgePointingFromRightDown = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingElectrifiedEdgePointingFromRightDown", file = "resources/conveyor_pLEFT_c(electrified_edge_fRIGHT_pDOWN).png")
conveyorPointingLeftContainingElectrifiedEdgePointingFromRightUp = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingElectrifiedEdgePointingFromRightUp", file = "resources/conveyor_pLEFT_c(electrified_edge_fRIGHT_pUP).png")
conveyorPointingLeftContainingElectrifiedEdgePointingFromUpLeft = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingElectrifiedEdgePointingFromUpLeft", file = "resources/conveyor_pLEFT_c(electrified_edge_fUP_pLEFT).png")
conveyorPointingLeftContainingElectrifiedEdgePointingFromUpRight = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingElectrifiedEdgePointingFromUpRight", file = "resources/conveyor_pLEFT_c(electrified_edge_fUP_pRIGHT).png")
conveyorPointingLeftContainingInverter = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingInverter", file = "resources/conveyor_pLEFT_c(inverter).png")
conveyorPointingLeftContainingElectrifiedInverter = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingElectrifiedInverter", file = "resources/conveyor_pLEFT_c(electrified_inverter).png")
conveyorPointingLeftContainingConveyorPointingUp = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingConveyorPointingUp", file = "resources/conveyor_pLEFT_c(conveyor_pUP).png")
conveyorPointingLeftContainingConveyorPointingLeft = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingConveyorPointingLeft", file = "resources/conveyor_pLEFT_c(conveyor_pLEFT).png")
conveyorPointingLeftContainingConveyorPointingDown = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingConveyorPointingDown", file = "resources/conveyor_pLEFT_c(conveyor_pDOWN).png")
conveyorPointingLeftContainingConveyorPointingRight = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingConveyorPointingRight", file = "resources/conveyor_pLEFT_c(conveyor_pRIGHT).png")
conveyorPointingLeftContainingBattery0PercentCharged = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingBattery0PercentCharged", file = "resources/conveyor_pLEFT_c(battery_0%).png")
conveyorPointingLeftContainingBattery50PercentCharged = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingBattery50PercentCharged", file = "resources/conveyor_pLEFT_c(battery_50%).png")
conveyorPointingLeftContainingBattery100PercentCharged = Cell(gets = "right", gives = "left", name = "ConveyorPointingLeftContainingBattery100PercentCharged", file = "resources/conveyor_pLEFT_c(battery_100%).png")

conveyorPointingRightContainingGenerator = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingGenerator", file = "resources/conveyor_pRIGHT_c(generator).png")
conveyorPointingRightContainingArrowPointingUp = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingArrowPointingUp", file = "resources/conveyor_pRIGHT_c(arrow_pUP).png")
conveyorPointingRightContainingArrowPointingDown = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingArrowPointingDown", file = "resources/conveyor_pRIGHT_c(arrow_pDOWN).png")
conveyorPointingRightContainingArrowPointingLeft = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingArrowPointingLeft", file = "resources/conveyor_pRIGHT_c(arrow_pLEFT).png")
conveyorPointingRightContainingArrowPointingRight = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingArrowPointingRight", file = "resources/conveyor_pRIGHT_c(arrow_pRIGHT).png")
conveyorPointingRightContainingElectrifiedArrowPointingUp = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingElectrifiedArrowPointingUp", file = "resources/conveyor_pRIGHT_c(electrified_arrow_pUP).png")
conveyorPointingRightContainingElectrifiedArrowPointingDown = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingElectrifiedArrowPointingDown", file = "resources/conveyor_pRIGHT_c(electrified_arrow_pDOWN).png")
conveyorPointingRightContainingElectrifiedArrowPointingLeft = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingElectrifiedArrowPointingLeft", file = "resources/conveyor_pRIGHT_c(electrified_arrow_pLEFT).png")
conveyorPointingRightContainingElectrifiedArrowPointingRight = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingElectrifiedArrowPointingRight", file = "resources/conveyor_pRIGHT_c(electrified_arrow_pRIGHT).png")
conveyorPointingRightContainingEdgePointingFromDownLeft = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingEdgePointingFromDownLeft", file = "resources/conveyor_pRIGHT_c(edge_fDOWN_pLEFT).png")
conveyorPointingRightContainingEdgePointingFromDownRight = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingEdgePointingFromDownRight", file = "resources/conveyor_pRIGHT_c(edge_fDOWN_pRIGHT).png")
conveyorPointingRightContainingEdgePointingFromLeftDown = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingEdgePointingFromLeftDown", file = "resources/conveyor_pRIGHT_c(edge_fLEFT_pDOWN).png")
conveyorPointingRightContainingEdgePointingFromLeftUp = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingEdgePointingFromLeftUp", file = "resources/conveyor_pRIGHT_c(edge_fLEFT_pUP).png")
conveyorPointingRightContainingEdgePointingFromRightDown = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingEdgePointingFromRightDown", file = "resources/conveyor_pRIGHT_c(edge_fRIGHT_pDOWN).png")
conveyorPointingRightContainingEdgePointingFromRightUp = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingEdgePointingFromRightUp", file = "resources/conveyor_pRIGHT_c(edge_fRIGHT_pUP).png")
conveyorPointingRightContainingEdgePointingFromUpLeft= Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingEdgePointingFromUpLeft", file = "resources/conveyor_pRIGHT_c(edge_fUP_pLEFT).png")
conveyorPointingRightContainingEdgePointingFromUpRight = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingEdgePointingFromUpRight", file = "resources/conveyor_pRIGHT_c(edge_fUP_pRIGHT).png")
conveyorPointingRightContainingElectrifiedEdgePointingFromDownLeft = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingElectrifiedEdgePointingFromDownLeft", file = "resources/conveyor_pRIGHT_c(electrified_edge_fDOWN_pLEFT).png")
conveyorPointingRightContainingElectrifiedEdgePointingFromDownRight = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingElectrifiedEdgePointingFromDownRight", file = "resources/conveyor_pRIGHT_c(electrified_edge_fDOWN_pRIGHT).png")
conveyorPointingRightContainingElectrifiedEdgePointingFromLeftDown = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingElectrifiedEdgePointingFromLeftDown", file = "resources/conveyor_pRIGHT_c(electrified_edge_fLEFT_pDOWN).png")
conveyorPointingRightContainingElectrifiedEdgePointingFromLeftUp = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingElectrifiedEdgePointingFromLeftUp", file = "resources/conveyor_pRIGHT_c(electrified_edge_fLEFT_pUP).png")
conveyorPointingRightContainingElectrifiedEdgePointingFromRightDown = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingElectrifiedEdgePointingFromRightDown", file = "resources/conveyor_pRIGHT_c(electrified_edge_fRIGHT_pDOWN).png")
conveyorPointingRightContainingElectrifiedEdgePointingFromRightUp = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingElectrifiedEdgePointingFromRightUp", file = "resources/conveyor_pRIGHT_c(electrified_edge_fRIGHT_pUP).png")
conveyorPointingRightContainingElectrifiedEdgePointingFromUpLeft = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingElectrifiedEdgePointingFromUpLeft", file = "resources/conveyor_pRIGHT_c(electrified_edge_fUP_pLEFT).png")
conveyorPointingRightContainingElectrifiedEdgePointingFromUpRight = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingElectrifiedEdgePointingFromUpRight", file = "resources/conveyor_pRIGHT_c(electrified_edge_fUP_pRIGHT).png")
conveyorPointingRightContainingInverter = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingInverter", file = "resources/conveyor_pRIGHT_c(inverter).png")
conveyorPointingRightContainingElectrifiedInverter = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingElectrifiedInverter", file = "resources/conveyor_pRIGHT_c(electrified_inverter).png")
conveyorPointingRightContainingConveyorPointingUp = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingConveyorPointingUp", file = "resources/conveyor_pRIGHT_c(conveyor_pUP).png")
conveyorPointingRightContainingConveyorPointingLeft = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingConveyorPointingLeft", file = "resources/conveyor_pRIGHT_c(conveyor_pLEFT).png")
conveyorPointingRightContainingConveyorPointingDown = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingConveyorPointingDown", file = "resources/conveyor_pRIGHT_c(conveyor_pDOWN).png")
conveyorPointingRightContainingConveyorPointingRight = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingConveyorPointingRight", file = "resources/conveyor_pRIGHT_c(conveyor_pRIGHT).png")
conveyorPointingRightContainingBattery0PercentCharged = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingBattery0PercentCharged", file = "resources/conveyor_pRIGHT_c(battery_0%).png")
conveyorPointingRightContainingBattery50PercentCharged = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingBattery50PercentCharged", file = "resources/conveyor_pRIGHT_c(battery_50%).png")
conveyorPointingRightContainingBattery100PercentCharged = Cell(gets = "left", gives = "right", name = "ConveyorPointingRightContainingBattery100PercentCharged", file = "resources/conveyor_pRIGHT_c(battery_100%).png")

conveyorPointingDownContainingGenerator = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingGenerator", file = "resources/conveyor_pDOWN_c(generator).png")
conveyorPointingDownContainingArrowPointingUp = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingArrowPointingUp", file = "resources/conveyor_pDOWN_c(arrow_pUP).png")
conveyorPointingDownContainingArrowPointingDown = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingArrowPointingDown", file = "resources/conveyor_pDOWN_c(arrow_pDOWN).png")
conveyorPointingDownContainingArrowPointingLeft = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingArrowPointingLeft", file = "resources/conveyor_pDOWN_c(arrow_pLEFT).png")
conveyorPointingDownContainingArrowPointingRight = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingArrowPointingRight", file = "resources/conveyor_pDOWN_c(arrow_pRIGHT).png")
conveyorPointingDownContainingElectrifiedArrowPointingUp = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingElectrifiedArrowPointingUp", file = "resources/conveyor_pDOWN_c(electrified_arrow_pUP).png")
conveyorPointingDownContainingElectrifiedArrowPointingDown = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingElectrifiedArrowPointingDown", file = "resources/conveyor_pDOWN_c(electrified_arrow_pDOWN).png")
conveyorPointingDownContainingElectrifiedArrowPointingLeft = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingElectrifiedArrowPointingLeft", file = "resources/conveyor_pDOWN_c(electrified_arrow_pLEFT).png")
conveyorPointingDownContainingElectrifiedArrowPointingRight = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingElectrifiedArrowPointingRight", file = "resources/conveyor_pDOWN_c(electrified_arrow_pRIGHT).png")
conveyorPointingDownContainingEdgePointingFromDownLeft = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingEdgePointingFromDownLeft", file = "resources/conveyor_pDOWN_c(edge_fDOWN_pLEFT).png")
conveyorPointingDownContainingEdgePointingFromDownRight = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingEdgePointingFromDownRight", file = "resources/conveyor_pDOWN_c(edge_fDOWN_pRIGHT).png")
conveyorPointingDownContainingEdgePointingFromLeftDown = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingEdgePointingFromLeftDown", file = "resources/conveyor_pDOWN_c(edge_fLEFT_pDOWN).png")
conveyorPointingDownContainingEdgePointingFromLeftUp = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingEdgePointingFromLeftUp", file = "resources/conveyor_pDOWN_c(edge_fLEFT_pUP).png")
conveyorPointingDownContainingEdgePointingFromRightDown = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingEdgePointingFromRightDown", file = "resources/conveyor_pDOWN_c(edge_fRIGHT_pDOWN).png")
conveyorPointingDownContainingEdgePointingFromRightUp = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingEdgePointingFromRightUp", file = "resources/conveyor_pDOWN_c(edge_fRIGHT_pUP).png")
conveyorPointingDownContainingEdgePointingFromUpLeft= Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingEdgePointingFromUpLeft", file = "resources/conveyor_pDOWN_c(edge_fUP_pLEFT).png")
conveyorPointingDownContainingEdgePointingFromUpRight = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingEdgePointingFromUpRight", file = "resources/conveyor_pDOWN_c(edge_fUP_pRIGHT).png")
conveyorPointingDownContainingElectrifiedEdgePointingFromDownLeft = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingElectrifiedEdgePointingFromDownLeft", file = "resources/conveyor_pDOWN_c(electrified_edge_fDOWN_pLEFT).png")
conveyorPointingDownContainingElectrifiedEdgePointingFromDownRight = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingElectrifiedEdgePointingFromDownRight", file = "resources/conveyor_pDOWN_c(electrified_edge_fDOWN_pRIGHT).png")
conveyorPointingDownContainingElectrifiedEdgePointingFromLeftDown = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingElectrifiedEdgePointingFromLeftDown", file = "resources/conveyor_pDOWN_c(electrified_edge_fLEFT_pDOWN).png")
conveyorPointingDownContainingElectrifiedEdgePointingFromLeftUp = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingElectrifiedEdgePointingFromLeftUp", file = "resources/conveyor_pDOWN_c(electrified_edge_fLEFT_pUP).png")
conveyorPointingDownContainingElectrifiedEdgePointingFromRightDown = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingElectrifiedEdgePointingFromRightDown", file = "resources/conveyor_pDOWN_c(electrified_edge_fRIGHT_pDOWN).png")
conveyorPointingDownContainingElectrifiedEdgePointingFromRightUp = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingElectrifiedEdgePointingFromRightUp", file = "resources/conveyor_pDOWN_c(electrified_edge_fRIGHT_pUP).png")
conveyorPointingDownContainingElectrifiedEdgePointingFromUpLeft = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingElectrifiedEdgePointingFromUpLeft", file = "resources/conveyor_pDOWN_c(electrified_edge_fUP_pLEFT).png")
conveyorPointingDownContainingElectrifiedEdgePointingFromUpRight = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingElectrifiedEdgePointingFromUpRight", file = "resources/conveyor_pDOWN_c(electrified_edge_fUP_pRIGHT).png")
conveyorPointingDownContainingInverter = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingInverter", file = "resources/conveyor_pDOWN_c(inverter).png")
conveyorPointingDownContainingElectrifiedInverter = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingElectrifiedInverter", file = "resources/conveyor_pDOWN_c(electrified_inverter).png")
conveyorPointingDownContainingConveyorPointingUp = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingConveyorPointingUp", file = "resources/conveyor_pDOWN_c(conveyor_pUP).png")
conveyorPointingDownContainingConveyorPointingLeft = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingConveyorPointingLeft", file = "resources/conveyor_pDOWN_c(conveyor_pLEFT).png")
conveyorPointingDownContainingConveyorPointingDown = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingConveyorPointingDown", file = "resources/conveyor_pDOWN_c(conveyor_pDOWN).png")
conveyorPointingDownContainingConveyorPointingRight = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingConveyorPointingRight", file = "resources/conveyor_pDOWN_c(conveyor_pRIGHT).png")
conveyorPointingDownContainingBattery0PercentCharged = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingBattery0PercentCharged", file = "resources/conveyor_pDOWN_c(battery_0%).png")
conveyorPointingDownContainingBattery50PercentCharged = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingBattery50PercentCharged", file = "resources/conveyor_pDOWN_c(battery_50%).png")
conveyorPointingDownContainingBattery100PercentCharged = Cell(gets = "up", gives = "down", name = "ConveyorPointingDownContainingBattery100PercentCharged", file = "resources/conveyor_pDOWN_c(battery_100%).png")

battery0PercentCharged = Cell(gets = None, gives = None, name = "Battery0PercentCharged", file = "resources/battery_0%.png")
battery50PercentCharged = Cell(gets = None, gives = None, name = "Battery50PercentCharged", file = "resources/battery_50%.png")
battery100PercentCharged = Cell(gets = None, gives = None, name = "Battery100PercentCharged", file = "resources/battery_100%.png")

#MENU ICONS
menuIconArrow = PhotoImage(file="resources/arrow_menu_icon.png")
menuIconGenerator = PhotoImage(file="resources/generator_menu_icon.png")
menuIconEraser = PhotoImage(file="resources/eraser_menu_icon.png")
menuIconConfigurator = PhotoImage(file="resources/configurator_menu_icon.png")
menuIconEdge = PhotoImage(file="resources/edge_menu_icon.png")
menuIconInverter = PhotoImage(file="resources/inverter_menu_icon.png")
menuIconConveyor = PhotoImage(file="resources/conveyor_menu_icon.png")
menuIconBattery = PhotoImage(file="resources/battery_menu_icon.png")